# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: otaku-stars-mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: otaku_stars
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
